packages:
  # all packages in subdirs
  - 'packages/service-backend'
  - 'packages/service-frontend'
  - 'packages/types'
  - 'packages/ui'
  - 'packages/api'
  - 'packages/tailwind-config'
  - 'script'
