import './globals.css'
import type { JSX } from 'react'

import localFont from 'next/font/local'

import Provider from './provider.client'

const pretendardFont = localFont({
  src: './font/PretendardVariable.woff2',
  fallback: [
    'Pretendard',
    '-apple-system',
    'BlinkMacSystemFont',
    'system-ui',
    'Roboto',
    'Helvetica Neue',
    'Segoe UI',
    'Apple SD Gothic Neo',
    'Noto Sans KR',
    'Malgun Gothic',
    'Apple Color Emoji',
    'Segoe UI Emoji',
    'Segoe UI Symbol',
    'sans-serif',
  ],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en" className={pretendardFont.className}>
      <Provider>
        <body className={pretendardFont.className}>{children}</body>
      </Provider>
    </html>
  )
}
