name: deploy-prod

on:
  release:
    types:
      - created

env:
  STAGE: 'prod'
  NEXT_PUBLIC_STAGE: 'prod'

  # AWS
  AWS_REGION: 'ap-northeast-2'
  AWS_HOST_ZONE: ${{ secrets.AWS_HOST_ZONE }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # DOMAIN
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  DOMAIN_NAME_API: api.${{ secrets.DOMAIN_NAME }}
  NEXT_PUBLIC_API_HOST: api.${{ secrets.DOMAIN_NAME }}
  S3_PRIVATE_BUCKET: ${{ secrets.S3_PRIVATE_BUCKET }}

  # SENTRY
  WEB_SENTRY_DSN: ${{ secrets.WEB_SENTRY_DSN }}

jobs:
  deploy-prod:
    name: deploy to production environment
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.6.3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Deploy production
        run: pnpm deploy:prod
